// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: payload.proto

package helloim_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文本消息
type TextPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPayload) Reset() {
	*x = TextPayload{}
	mi := &file_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPayload) ProtoMessage() {}

func (x *TextPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPayload.ProtoReflect.Descriptor instead.
func (*TextPayload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{0}
}

func (x *TextPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 图片消息
type ImagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePayload) Reset() {
	*x = ImagePayload{}
	mi := &file_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePayload) ProtoMessage() {}

func (x *ImagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePayload.ProtoReflect.Descriptor instead.
func (*ImagePayload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{1}
}

func (x *ImagePayload) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// 文件消息
type FilePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=fileUrl,proto3" json:"fileUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePayload) Reset() {
	*x = FilePayload{}
	mi := &file_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePayload) ProtoMessage() {}

func (x *FilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePayload.ProtoReflect.Descriptor instead.
func (*FilePayload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{2}
}

func (x *FilePayload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FilePayload) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

// 已读回执
type ReceiptPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`         // 已读的消息id
	ServerSeq     int64                  `protobuf:"varint,2,opt,name=serverSeq,proto3" json:"serverSeq,omitempty"` // 已读消息的服务端序号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptPayload) Reset() {
	*x = ReceiptPayload{}
	mi := &file_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptPayload) ProtoMessage() {}

func (x *ReceiptPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptPayload.ProtoReflect.Descriptor instead.
func (*ReceiptPayload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{3}
}

func (x *ReceiptPayload) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ReceiptPayload) GetServerSeq() int64 {
	if x != nil {
		return x.ServerSeq
	}
	return 0
}

type Payload struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PayloadType PayloadType            `protobuf:"varint,1,opt,name=payloadType,proto3,enum=helloim.protocol.PayloadType" json:"payloadType,omitempty"` // 消息类型
	At          bool                   `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`                                                     // 是否@人, 群聊场景使用
	AtUid       []string               `protobuf:"bytes,3,rep,name=atUid,proto3" json:"atUid,omitempty"`                                                // 被@的人, 群聊场景使用
	// Types that are valid to be assigned to Content:
	//
	//	*Payload_Text
	//	*Payload_Image
	Content       isPayload_Content `protobuf_oneof:"Content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_payload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{4}
}

func (x *Payload) GetPayloadType() PayloadType {
	if x != nil {
		return x.PayloadType
	}
	return PayloadType_TEXT
}

func (x *Payload) GetAt() bool {
	if x != nil {
		return x.At
	}
	return false
}

func (x *Payload) GetAtUid() []string {
	if x != nil {
		return x.AtUid
	}
	return nil
}

func (x *Payload) GetContent() isPayload_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Payload) GetText() *TextPayload {
	if x != nil {
		if x, ok := x.Content.(*Payload_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Payload) GetImage() *ImagePayload {
	if x != nil {
		if x, ok := x.Content.(*Payload_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isPayload_Content interface {
	isPayload_Content()
}

type Payload_Text struct {
	Text *TextPayload `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type Payload_Image struct {
	Image *ImagePayload `protobuf:"bytes,5,opt,name=image,proto3,oneof"`
}

func (*Payload_Text) isPayload_Content() {}

func (*Payload_Image) isPayload_Content() {}

var File_payload_proto protoreflect.FileDescriptor

const file_payload_proto_rawDesc = "" +
	"\n" +
	"\rpayload.proto\x12\x10helloim.protocol\x1a\x12payload_type.proto\"'\n" +
	"\vTextPayload\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"*\n" +
	"\fImagePayload\x12\x1a\n" +
	"\bimageUrl\x18\x01 \x01(\tR\bimageUrl\"C\n" +
	"\vFilePayload\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\afileUrl\x18\x02 \x01(\tR\afileUrl\"D\n" +
	"\x0eReceiptPayload\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x03R\x05msgId\x12\x1c\n" +
	"\tserverSeq\x18\x02 \x01(\x03R\tserverSeq\"\xe8\x01\n" +
	"\aPayload\x12?\n" +
	"\vpayloadType\x18\x01 \x01(\x0e2\x1d.helloim.protocol.PayloadTypeR\vpayloadType\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\bR\x02at\x12\x14\n" +
	"\x05atUid\x18\x03 \x03(\tR\x05atUid\x123\n" +
	"\x04text\x18\x04 \x01(\v2\x1d.helloim.protocol.TextPayloadH\x00R\x04text\x126\n" +
	"\x05image\x18\x05 \x01(\v2\x1e.helloim.protocol.ImagePayloadH\x00R\x05imageB\t\n" +
	"\aContentB\x7f\n" +
	",com.github.xuning888.helloim.common.protobufB\fPayloadProtoP\x01Z?github.com/xuning888/helloIMClient/internal/proto;helloim_protob\x06proto3"

var (
	file_payload_proto_rawDescOnce sync.Once
	file_payload_proto_rawDescData []byte
)

func file_payload_proto_rawDescGZIP() []byte {
	file_payload_proto_rawDescOnce.Do(func() {
		file_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)))
	})
	return file_payload_proto_rawDescData
}

var file_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payload_proto_goTypes = []any{
	(*TextPayload)(nil),    // 0: helloim.protocol.TextPayload
	(*ImagePayload)(nil),   // 1: helloim.protocol.ImagePayload
	(*FilePayload)(nil),    // 2: helloim.protocol.FilePayload
	(*ReceiptPayload)(nil), // 3: helloim.protocol.ReceiptPayload
	(*Payload)(nil),        // 4: helloim.protocol.Payload
	(PayloadType)(0),       // 5: helloim.protocol.PayloadType
}
var file_payload_proto_depIdxs = []int32{
	5, // 0: helloim.protocol.Payload.payloadType:type_name -> helloim.protocol.PayloadType
	0, // 1: helloim.protocol.Payload.text:type_name -> helloim.protocol.TextPayload
	1, // 2: helloim.protocol.Payload.image:type_name -> helloim.protocol.ImagePayload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payload_proto_init() }
func file_payload_proto_init() {
	if File_payload_proto != nil {
		return
	}
	file_payload_type_proto_init()
	file_payload_proto_msgTypes[4].OneofWrappers = []any{
		(*Payload_Text)(nil),
		(*Payload_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_proto_goTypes,
		DependencyIndexes: file_payload_proto_depIdxs,
		MessageInfos:      file_payload_proto_msgTypes,
	}.Build()
	File_payload_proto = out.File
	file_payload_proto_goTypes = nil
	file_payload_proto_depIdxs = nil
}
