// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: payload_type.proto

package helloim_proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadType int32

const (
	PayloadType_TEXT    PayloadType = 0 // 文本
	PayloadType_IMAGE   PayloadType = 1 // 图片消息
	PayloadType_RECEIPT PayloadType = 2 // 已读回执
	PayloadType_FILE    PayloadType = 3 // 文件消息
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "RECEIPT",
		3: "FILE",
	}
	PayloadType_value = map[string]int32{
		"TEXT":    0,
		"IMAGE":   1,
		"RECEIPT": 2,
		"FILE":    3,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_type_proto_enumTypes[0].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_payload_type_proto_enumTypes[0]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_payload_type_proto_rawDescGZIP(), []int{0}
}

var File_payload_type_proto protoreflect.FileDescriptor

const file_payload_type_proto_rawDesc = "" +
	"\n" +
	"\x12payload_type.proto\x12\x10helloim.protocol*9\n" +
	"\vPayloadType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\v\n" +
	"\aRECEIPT\x10\x02\x12\b\n" +
	"\x04FILE\x10\x03B\x83\x01\n" +
	",com.github.xuning888.helloim.common.protobufB\x10PayloadTypeProtoP\x01Z?github.com/xuning888/helloIMClient/internal/proto;helloim_protob\x06proto3"

var (
	file_payload_type_proto_rawDescOnce sync.Once
	file_payload_type_proto_rawDescData []byte
)

func file_payload_type_proto_rawDescGZIP() []byte {
	file_payload_type_proto_rawDescOnce.Do(func() {
		file_payload_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_type_proto_rawDesc), len(file_payload_type_proto_rawDesc)))
	})
	return file_payload_type_proto_rawDescData
}

var file_payload_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payload_type_proto_goTypes = []any{
	(PayloadType)(0), // 0: helloim.protocol.PayloadType
}
var file_payload_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payload_type_proto_init() }
func file_payload_type_proto_init() {
	if File_payload_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_type_proto_rawDesc), len(file_payload_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_type_proto_goTypes,
		DependencyIndexes: file_payload_type_proto_depIdxs,
		EnumInfos:         file_payload_type_proto_enumTypes,
	}.Build()
	File_payload_type_proto = out.File
	file_payload_type_proto_goTypes = nil
	file_payload_type_proto_depIdxs = nil
}
