// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: send.proto

package helloim_proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPktRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // 消息发送方的uid
	FromUserType  int32                  `protobuf:"varint,2,opt,name=fromUserType,proto3" json:"fromUserType,omitempty"`
	ChatId        string                 `protobuf:"bytes,3,opt,name=chatId,proto3" json:"chatId,omitempty"`                // 消息接收方的会话id
	ChatType      int32                  `protobuf:"varint,4,opt,name=chatType,proto3" json:"chatType,omitempty"`           // 消息接收方的会话类型
	SendTimestamp int64                  `protobuf:"varint,5,opt,name=sendTimestamp,proto3" json:"sendTimestamp,omitempty"` // 发送消息的时间戳
	ToUserType    int32                  `protobuf:"varint,6,opt,name=toUserType,proto3" json:"toUserType,omitempty"`       // 消息接收方的userType
	Payload       *Payload               `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`              // 消息内容
	Extra         string                 `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`                  // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPktRequest) Reset() {
	*x = SendPktRequest{}
	mi := &file_send_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPktRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPktRequest) ProtoMessage() {}

func (x *SendPktRequest) ProtoReflect() protoreflect.Message {
	mi := &file_send_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPktRequest.ProtoReflect.Descriptor instead.
func (*SendPktRequest) Descriptor() ([]byte, []int) {
	return file_send_proto_rawDescGZIP(), []int{0}
}

func (x *SendPktRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendPktRequest) GetFromUserType() int32 {
	if x != nil {
		return x.FromUserType
	}
	return 0
}

func (x *SendPktRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendPktRequest) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *SendPktRequest) GetSendTimestamp() int64 {
	if x != nil {
		return x.SendTimestamp
	}
	return 0
}

func (x *SendPktRequest) GetToUserType() int32 {
	if x != nil {
		return x.ToUserType
	}
	return 0
}

func (x *SendPktRequest) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendPktRequest) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type SendPktResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`         // 消息ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 收到上行消息的时间戳
	ServerSeq     int64                  `protobuf:"varint,3,opt,name=serverSeq,proto3" json:"serverSeq,omitempty"` // 服务端消息序号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPktResponse) Reset() {
	*x = SendPktResponse{}
	mi := &file_send_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPktResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPktResponse) ProtoMessage() {}

func (x *SendPktResponse) ProtoReflect() protoreflect.Message {
	mi := &file_send_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPktResponse.ProtoReflect.Descriptor instead.
func (*SendPktResponse) Descriptor() ([]byte, []int) {
	return file_send_proto_rawDescGZIP(), []int{1}
}

func (x *SendPktResponse) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendPktResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendPktResponse) GetServerSeq() int64 {
	if x != nil {
		return x.ServerSeq
	}
	return 0
}

var File_send_proto protoreflect.FileDescriptor

const file_send_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"send.proto\x12\x10helloim.protocol\x1a\rpayload.proto\"\x8d\x02\n" +
	"\x0eSendPktRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\"\n" +
	"\ffromUserType\x18\x02 \x01(\x05R\ffromUserType\x12\x16\n" +
	"\x06chatId\x18\x03 \x01(\tR\x06chatId\x12\x1a\n" +
	"\bchatType\x18\x04 \x01(\x05R\bchatType\x12$\n" +
	"\rsendTimestamp\x18\x05 \x01(\x03R\rsendTimestamp\x12\x1e\n" +
	"\n" +
	"toUserType\x18\x06 \x01(\x05R\n" +
	"toUserType\x123\n" +
	"\apayload\x18\a \x01(\v2\x19.helloim.protocol.PayloadR\apayload\x12\x14\n" +
	"\x05extra\x18\b \x01(\tR\x05extra\"c\n" +
	"\x0fSendPktResponse\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\x03R\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tserverSeq\x18\x03 \x01(\x03R\tserverSeqB\x7f\n" +
	",com.github.xuning888.helloim.common.protobufB\fSendPktProtoP\x01Z?github.com/xuning888/helloIMClient/internal/proto;helloim_protob\x06proto3"

var (
	file_send_proto_rawDescOnce sync.Once
	file_send_proto_rawDescData []byte
)

func file_send_proto_rawDescGZIP() []byte {
	file_send_proto_rawDescOnce.Do(func() {
		file_send_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_send_proto_rawDesc), len(file_send_proto_rawDesc)))
	})
	return file_send_proto_rawDescData
}

var file_send_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_send_proto_goTypes = []any{
	(*SendPktRequest)(nil),  // 0: helloim.protocol.SendPktRequest
	(*SendPktResponse)(nil), // 1: helloim.protocol.SendPktResponse
	(*Payload)(nil),         // 2: helloim.protocol.Payload
}
var file_send_proto_depIdxs = []int32{
	2, // 0: helloim.protocol.SendPktRequest.payload:type_name -> helloim.protocol.Payload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_send_proto_init() }
func file_send_proto_init() {
	if File_send_proto != nil {
		return
	}
	file_payload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_send_proto_rawDesc), len(file_send_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_send_proto_goTypes,
		DependencyIndexes: file_send_proto_depIdxs,
		MessageInfos:      file_send_proto_msgTypes,
	}.Build()
	File_send_proto = out.File
	file_send_proto_goTypes = nil
	file_send_proto_depIdxs = nil
}
