// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.25.3
// source: cmdId.proto

package helloim_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdId int32

const (
	CmdId_CMD_ID_DEFAULT CmdId = 0
	CmdId_CMD_ID_ECHO    CmdId = 1    // echo
	CmdId_CMD_ID_AUTH    CmdId = 2    // AUTH
	CmdId_CMD_ID_C2CSEND CmdId = 1006 // 单聊上行
	CmdId_CMD_ID_C2CPUSH CmdId = 1007 // 单聊下行
	CmdId_CMD_ID_C2GSEND CmdId = 1008 // 群聊上行
	CmdId_CMD_ID_C2GPUSH CmdId = 1009 // 群聊下行
)

// Enum value maps for CmdId.
var (
	CmdId_name = map[int32]string{
		0:    "CMD_ID_DEFAULT",
		1:    "CMD_ID_ECHO",
		2:    "CMD_ID_AUTH",
		1006: "CMD_ID_C2CSEND",
		1007: "CMD_ID_C2CPUSH",
		1008: "CMD_ID_C2GSEND",
		1009: "CMD_ID_C2GPUSH",
	}
	CmdId_value = map[string]int32{
		"CMD_ID_DEFAULT": 0,
		"CMD_ID_ECHO":    1,
		"CMD_ID_AUTH":    2,
		"CMD_ID_C2CSEND": 1006,
		"CMD_ID_C2CPUSH": 1007,
		"CMD_ID_C2GSEND": 1008,
		"CMD_ID_C2GPUSH": 1009,
	}
)

func (x CmdId) Enum() *CmdId {
	p := new(CmdId)
	*p = x
	return p
}

func (x CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_cmdId_proto_enumTypes[0].Descriptor()
}

func (CmdId) Type() protoreflect.EnumType {
	return &file_cmdId_proto_enumTypes[0]
}

func (x CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdId.Descriptor instead.
func (CmdId) EnumDescriptor() ([]byte, []int) {
	return file_cmdId_proto_rawDescGZIP(), []int{0}
}

var File_cmdId_proto protoreflect.FileDescriptor

const file_cmdId_proto_rawDesc = "" +
	"\n" +
	"\vcmdId.proto\x12\x10helloim.protocol*\x91\x01\n" +
	"\x05CmdId\x12\x12\n" +
	"\x0eCMD_ID_DEFAULT\x10\x00\x12\x0f\n" +
	"\vCMD_ID_ECHO\x10\x01\x12\x0f\n" +
	"\vCMD_ID_AUTH\x10\x02\x12\x13\n" +
	"\x0eCMD_ID_C2CSEND\x10\xee\a\x12\x13\n" +
	"\x0eCMD_ID_C2CPUSH\x10\xef\a\x12\x13\n" +
	"\x0eCMD_ID_C2GSEND\x10\xf0\a\x12\x13\n" +
	"\x0eCMD_ID_C2GPUSH\x10\xf1\aBy\n" +
	".com.github.xuning888.helloim.contract.protobufB\x06MsgCmdZ?github.com/xuning888/helloIMClient/internal/proto;helloim_protob\x06proto3"

var (
	file_cmdId_proto_rawDescOnce sync.Once
	file_cmdId_proto_rawDescData []byte
)

func file_cmdId_proto_rawDescGZIP() []byte {
	file_cmdId_proto_rawDescOnce.Do(func() {
		file_cmdId_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmdId_proto_rawDesc), len(file_cmdId_proto_rawDesc)))
	})
	return file_cmdId_proto_rawDescData
}

var file_cmdId_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmdId_proto_goTypes = []any{
	(CmdId)(0), // 0: helloim.protocol.CmdId
}
var file_cmdId_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmdId_proto_init() }
func file_cmdId_proto_init() {
	if File_cmdId_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmdId_proto_rawDesc), len(file_cmdId_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmdId_proto_goTypes,
		DependencyIndexes: file_cmdId_proto_depIdxs,
		EnumInfos:         file_cmdId_proto_enumTypes,
	}.Build()
	File_cmdId_proto = out.File
	file_cmdId_proto_goTypes = nil
	file_cmdId_proto_depIdxs = nil
}
